version: '3.1'
services:
  next-db:
    image: postgres
    restart: unless-stopped
    env_file: '.env'
    # volumes:
    #   - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '5987:5432'
  
  db-adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 5577:8080

